name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions: write-all      
   
jobs:
   read_config:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2

       - name: Dynamically Call Workflow
         env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WORKFLOW_PAT: ${{ secrets.WORKFLOW_PAT }}
          ACTIONS_STEP_DEBUG: true

         run: |
          PAT="${{ env.WORKFLOW_PAT }}" 
          echo "My PAT Token: $PAT"  

   pipeline:
    uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@main     
   
    
