name: Java maven build

on:
  workflow_call:
    inputs:
      pipelineType:
        required: true
        type: string
      buildTool:
        required: true
        type: string

  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  my_job:
    name: deploy
    uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@main
  

    
