name: Main Workflow

on:
  workflow_dispatch:
  push:
    branches:
      - main
      
permissions: write-all      
   
jobs:
   read_config:
     runs-on: ubuntu-latest
     steps:
       - name: Checkout code
         uses: actions/checkout@v2

   pipeline:
    uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@29fb3ba9d0980a18d577a916d2055f7af21f8929     
   
    
