name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
     inputs:
      CICD_pipeline:
        description: 'Ù‹Workflow pipeline'
        required: true
        default: 'CICD_pipeline'

      CICD_pipeline_github_account:
        description: 'GitHub Account Owner'
        required: true
        default: ':userName'

      CICD_pipeline_repo_github:
        description: 'repo-name'
        required: true
        default: ':repoName' 
  
jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo curl -sL https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read pipelineconfig
        id: read_config
        run: |
          pipeline_config_path="${{ github.workspace }}/pipelineconfig.yml"

          # Use a tool like yq to parse the YAML file (install yq if needed)
          pipelineTtype=$(yq eval '.pipelineType' "${pipeline_config_path}")
          buildTool=$(yq eval '.buildTool' "${pipeline_config_path}")
          echo "PipelineType: $pipelineType"
          echo "BuildTool: $buildTool"
          echo "::set-output name=pipelineType::$pipelineType"
          echo "::set-output name=buildTool::$BuildTool"  
          
      - name: "ðŸ“¦ Trigger Project Test"
        uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@main
        env:
          PAYLOAD_AUTHOR: Aish199
          PAYLOAD_REVISION: "3"
        with:
          repository: Aish19999/DevOps_templet
          event: CICD_pipeline
          github_pat: ${{ secrets.ACTIONS_KEY }}
        

           
             
          

         
      
    




