name: Main Workflow

on:
  push:
    branches:
      - main
      - feature-test
  
jobs:
  read_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq and yq
        uses: Aish1999/DevOps_templet/.github/workflows/actions.yml@main
          

        

           
             
          

         
      
    




