name: Java maven build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build_test:

    runs-on: ubuntu-latest

    steps:
    - uses: action/checkout@v3
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'termurin'
        cache: maven
    - name: Build with maven
      run: mvn -B pacakage --file pom.xml
