name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Reusable Workflow
        uses: actions/checkout@v2

      - name: Trigger Reusable Workflow
        uses: ad-m/github-push-action@v0.5.0
        with:
          repository: Aish19999/DevOps_templet  # Replace with your repository
          github_token: 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
          branch: main
          workflow_path: .github/workflows/actions.yml
          workflow_inputs: |
            {
              "pipelineType": "Java",
              "buildTool": "Maven"
            }

