name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Reusable Workflow
        uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@main


