name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_call:
  
jobs:
  read_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Read pipelineconfig
        id: read_config
        run: |
          PipelineType=$(cat pipelineconfig.yml | yq r - PipelineType)
          BuildTool=$(cat pipelineconfig.yml | yq r - buildtool)
          echo "PipelineType: $PipelineType"
          echo "BuildTool: $BuildTool"
          echo "::set-output name=PipelineType::$PipelineType"
          echo "::set-output name=BuildTool::$BuildTool"

         
      
    




