name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_call:
  
jobs:
  read_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo curl -sL https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read pipelineconfig
        id: read_config
        run: |
          pipeline_config_path="${{ github.workspace }}/pipelineconfig.yml"

          # Use a tool like yq to parse the YAML file (install yq if needed)
          pipelineTtype=$(yq eval '.pipelineType' "${pipeline_config_path}")
          buildTool=$(yq eval '.buildTool' "${pipeline_config_path}")
          echo "PipelineType: $pipelineType"
          echo "BuildTool: $buildTool"
          echo "::set-output name=pipelineType::$pipelineType"
          echo "::set-output name=buildTool::$BuildTool"  
          
      - name: Trigger Second Workflow
        uses: actions/github-script@v5
        with:
          github-token: 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
          script: |
           const pipelinetype = "${{ steps.parse-config.outputs.pipelinetype }}";
           const buildtool = "${{ steps.parse-config.outputs.buildtool }}";
          uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@main 

           
             
          

         
      
    




