name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_call:
  
jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - name: Read pipelineConfig.yml
        run: |
          # Define the path to the pipelineConfig.yml file
          pipeline_config_path="${{ github.workspace }}/pipelineconfig.yml"

          # Use a tool like yq to parse the YAML file (install yq if needed)
          pipeline_type=$(yq eval '.pipelineType' "${pipeline_config_path}")
          buildTool=$(yq eval '.buildTool' "${pipeline_config_path}")
          echo "::set-output name=pipelinetype::$pipelinetype"
          echo "::set-output name=buildtool::$buildtool"
        shell: bash

      
     

         
      
    




