name: Java maven build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  my_job:
    name: deploy
    runs-on: ubuntu-18.04
  compile:
    uses: DevOps_templet.github/workflows/actions.yml
  

    
