name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  trigger-reusable-workflow:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Reusable Workflow
        uses: actions/checkout@v2
        
      - name: Set Git Configuration
        run: |
          git config --global --add safe.directory /github/workspace
          
      - name: Trigger Reusable Workflow
        uses: ad-m/github-push-action@v0.5.0
        with:
          repository: Aish19999/DevOps_templet/.github/workflows/actions.yml@main 
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
          workflow_path: .github/workflows/reusable_workflow.yml
          workflow_inputs: |
            {
              "pipelineType": "java",
              "buildTool": "maven"
            }



    

  

    
