name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_call:
  
jobs:
  read_config:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install jq and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq
          sudo curl -sL https://github.com/mikefarah/yq/releases/download/v4.13.2/yq_linux_amd64 -o /usr/bin/yq
          sudo chmod +x /usr/bin/yq

      - name: Read pipelineconfig
        id: read_config
        run: |
          pipeline_config_path="${{ github.workspace }}/pipelineconfig.yml"

          # Use a tool like yq to parse the YAML file (install yq if needed)
          pipeline_type=$(yq eval '.pipelineType' "${pipeline_config_path}")
          buildTool=$(yq eval '.buildTool' "${pipeline_config_path}")
          echo "PipelineType: $pipeline_type"
          echo "BuildTool: $buildTool"
          echo "::set-output name=pipelineType::$PipelineType"
          echo "::set-output name=buildTool::$BuildTool"  

      - name: Trigger Workflow 2
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { data: workflow } = await octokit.rest.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_id: 'DevOps_templet.github/workflows/actions.yml',  // Replace with the actual workflow name
              ref: 'main',  // Replace with the branch name if necessary
              inputs: {
                PipelineType: ${{ steps.read_config.outputs.PipelineType }},
                BuildTool: ${{ steps.read_config.outputs.BuildTool }}
              }
            });
            console.log(workflow);          
          

         
      
    




