name: Main Workflow

on:
  push:
    branches:
      - main
  workflow_call:
  
jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@main
      
    




