name: Java maven build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  my_job:
    name: deploy
    uses: Aish19999/DevOps_templet/.github/workflows/actions.yml@main
  

    
